### ISSUE TITLE
puppetlabs-apt deprecations and gpg warnings

### ISSUE THREAD

**Issue by igalic** [jamesnetherton/puppet-google-chrome#19]
i'm using the most recent (v2.2.2) version of `puppetlabs-apt`, so i'm getting a handful of warnings:
```
$include_src is deprecated and will be removed in the next major release
$key_src is deprecated and will be removed in the next major release
```
These are easy fixes, but most important is this one:

```
The id should be a full fingerprint (40 characters)
```

**Comment by jamesnetherton** [comment]
Are you using the latest version of the chrome module? These issues should have been cleaned up some time ago (starting from the 0.2.0 release I think).

**Comment by igalic** [comment]
the problem appears to be, that `puppet module install` chose 0.1.0, based on my versions of puppetlabs-apt (v2.3.0) and puppetlabs-stdlib (v4.12.0)

**Comment by jamesnetherton** [comment]
Yes, your're right. The current apt module version range is `>=1.4.2 <=2.2.0` so when > 2.2.0 is installed the chrome module install falls back to 0.1.0 which has the more open range.

I'll fix shortly and release a new version to the forge.

**Comment by igalic** [comment]
tested the release and it works perfectly fine!
thank you very much
