### ISSUE TITLE
Chrome cron script overrides HTTPS repository URL configuration on Red Hat variants

### ISSUE THREAD

**Issue by jamesnetherton** [jamesnetherton/puppet-google-chrome#36]
Even if the initial Puppet run configures the the Chrome yum repository URL to use HTTPS, this gets silently overwritten back to standard HTTP by the `/etc/cron.daily/google-chrome` script.

On Debian / Ubuntu, the cron script has a `REPOCONFIGREGEX`  variable which checks for `https`. The Red Hat flavour has no such check.

**Comment by jamesnetherton** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1050459

**Comment by meskaya** [comment]
Can you do a release with only Ubuntu using https ?

**Comment by jamesnetherton** [comment]
I just published 0.8.0 which uses https repo URLs for Debian OS flavours.

**Comment by meskaya** [comment]
Thanks a lot @jamesnetherton.
I hope we can get a fix for CentOS soon.
