### ISSUE TITLE
Unable to locate package google-chrome-stable on first run.

### ISSUE THREAD

**Issue by kwv** [jamesnetherton/puppet-google-chrome#7]
I'm including puppet-google-chrome via `include 'google_chrome'` as part of a vagrant provisioning block of a ubuntu/trusty64 box.   

Upon `vagrant up`, apt-sources is written as expected, but the install fails to locate package 'google-chrome-stable'.  After a subsequent `vagrant reload --provision`  everything works. 

I'm also including puppetlabs-apt to add another ppa. Could this be a case of not playing well together?

```
==> default: Debug: /Stage[main]/Google_chrome::Config/Apt::Source[google-chrome]/Apt::Setting[list-google-chrome]/File[/etc/apt/sources.list.d/google-chrome.list]: Autorequiring File[sources.list.d]
==> default: Info: Applying configuration version '1449248973'
==> default: Debug: Prefetching apt resources for package
==> default: Debug: Executing '/usr/bin/dpkg-query -W --showformat '${Status} ${Package} ${Version}\n''
==> default: Debug: Prefetching apt_key resources for apt_key
==> default: Debug: Executing '/usr/bin/apt-key adv --list-keys --with-colons --fingerprint --fixed-list-mode'
==> default: Debug: Executing '/usr/bin/gpg --with-fingerprint --with-colons /tmp/apt_key20151204-2179-15kyp5t | awk -F: '/^fpr:/ { print $10 }''
==> default: Debug: Executing '/usr/bin/apt-key add /tmp/apt_key20151204-2179-15kyp5t'
==> default: Notice: /Stage[main]/Google_chrome::Config/Apt::Source[google-chrome]/Apt::Key[Add key: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 from Apt::Source google-chrome]/Apt_key[Add key: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 from Apt::Source google-chrome]/ensure: created ==> default:
==> default: Debug: /Stage[main]/Google_chrome::Config/Apt::Source[google-chrome]/Apt::Key[Add key: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 from Apt::Source google-chrome]/Apt_key[Add key: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 from Apt::Source google-chrome]: The container Apt::Key[Add key: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 from Apt::Source google-chrome] will propagate my refresh event

==> default: Debug: Apt::Key[Add key: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 from Apt::Source google-chrome]: The container Apt::Source[google-chrome] will propagate my refresh event
==> default: Notice: /Stage[main]/Google_chrome::Config/Apt::Source[google-chrome]/Apt::Setting[list-google-chrome]/File[/etc/apt/sources.list.d/google-chrome.list]/ensure: created
==> default: Info: /Stage[main]/Google_chrome::Config/Apt::Source[google-chrome]/Apt::Setting[list-google-chrome]/File[/etc/apt/sources.list.d/google-chrome.list]: Scheduling refresh of Class[Apt::Update]
==> default: Debug: /Stage[main]/Google_chrome::Config/Apt::Source[google-chrome]/Apt::Setting[list-google-chrome]/File[/etc/apt/sources.list.d/google-chrome.list]: The container Apt::Setting[list-google-chrome] will propagate my refresh event
==> default: Debug: Apt::Setting[list-google-chrome]: The container Apt::Source[google-chrome] will propagate my refresh event
==> default: Debug: Apt::Source[google-chrome]: The container Class[Google_chrome::Config] will propagate my refresh event
==> default: Debug: Class[Google_chrome::Config]: The container Stage[main] will propagate my refresh event
==> default: Debug: Executing '/usr/bin/dpkg-query -W --showformat '${Status} ${Package} ${Version}\n' google-chrome-stable'
==> default: Debug: Executing '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install google-chrome-stable'
==> default: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install google-chrome-stable' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: E: Unable to locate package google-chrome-stable
==> default: Error: /Stage[main]/Google_chrome::Install/Package[google-chrome-stable]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install google-chrome-stable' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: E: Unable to locate package google-chrome-stable
```

**Comment by jamesnetherton** [comment]
I have seen this before but I thought I had it fixed. My multi-platform CI tests pass ok but maybe this is a false positive.

I'll test things out on Vagrant to see if I can reproduce the problem.

**Comment by jamesnetherton** [comment]
Reproduced it...
<pre>
==> default: Info: Applying configuration version '1449307974'
==> default: Debug: Prefetching apt_key resources for apt_key
==> default: Debug: Executing '/usr/bin/apt-key adv --list-keys --with-colons --fingerprint --fixed-list-mode'
==> default: Debug: Executing '/usr/bin/gpg --with-fingerprint --with-colons /tmp/apt_key20151205-1868-17jd11s | awk -F: '/^fpr:/ { print $10 }''
==> default: Debug: Executing '/usr/bin/apt-key add /tmp/apt_key20151205-1868-17jd11s'
==> default: Notice: /Stage[main]/Google_chrome::Config/Apt::Source[google-chrome]/Apt::Key[Add key: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 from Apt::Source google-chrome]/Apt_key[Add key: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 from Apt::Source google-chrome]/ensure: created
==> default: Debug: /Stage[main]/Google_chrome::Config/Apt::Source[google-chrome]/Apt::Key[Add key: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 from Apt::Source google-chrome]/Apt_key[Add key: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 from Apt::Source google-chrome]: The container Apt::Key[Add key: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 from Apt::Source google-chrome] will propagate my refresh event
==> default: Debug: Apt::Key[Add key: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 from Apt::Source google-chrome]: The container Apt::Source[google-chrome] will propagate my refresh event
==> default: Notice: /Stage[main]/Google_chrome::Config/Apt::Source[google-chrome]/Apt::Setting[list-google-chrome]/File[/etc/apt/sources.list.d/google-chrome.list]/ensure: created
==> default: Info: /Stage[main]/Google_chrome::Config/Apt::Source[google-chrome]/Apt::Setting[list-google-chrome]/File[/etc/apt/sources.list.d/google-chrome.list]: Scheduling refresh of Class[Apt::Update]
==> default: Debug: /Stage[main]/Google_chrome::Config/Apt::Source[google-chrome]/Apt::Setting[list-google-chrome]/File[/etc/apt/sources.list.d/google-chrome.list]: The container Apt::Setting[list-google-chrome] will propagate my refresh event
==> default: Debug: Apt::Setting[list-google-chrome]: The container Apt::Source[google-chrome] will propagate my refresh event
==> default: Debug: Apt::Source[google-chrome]: The container Class[Google_chrome::Config] will propagate my refresh event
==> default: Debug: Class[Google_chrome::Config]: The container Stage[main] will propagate my refresh event
==> default: Info: /Stage[main]/Apt/Apt::Setting[conf-update-stamp]/File[/etc/apt/apt.conf.d/15update-stamp]: Filebucketed /etc/apt/apt.conf.d/15update-stamp to puppet with sum b9de0ac9e2c9854b1bb213e362dc4e41
==> default: Notice: /Stage[main]/Apt/Apt::Setting[conf-update-stamp]/File[/etc/apt/apt.conf.d/15update-stamp]/content: content changed '{md5}b9de0ac9e2c9854b1bb213e362dc4e41' to '{md5}0962d70c4ec78bbfa6f3544ae0c41974'
==> default: Info: /Stage[main]/Apt/Apt::Setting[conf-update-stamp]/File[/etc/apt/apt.conf.d/15update-stamp]: Scheduling refresh of Class[Apt::Update]
==> default: Debug: /Stage[main]/Apt/Apt::Setting[conf-update-stamp]/File[/etc/apt/apt.conf.d/15update-stamp]: The container Apt::Setting[conf-update-stamp] will propagate my refresh event
==> default: Debug: Apt::Setting[conf-update-stamp]: The container Class[Apt] will propagate my refresh event
==> default: Debug: Prefetching apt resources for package
==> default: Debug: Executing '/usr/bin/dpkg-query -W --showformat '${Status} ${Package} ${Version}\n''
==> default: Debug: Executing '/usr/bin/dpkg-query -W --showformat '${Status} ${Package} ${Version}\n' google-chrome-stable'
<strong>==> default: Debug: Executing '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install google-chrome-stable'</strong>
==> default: Notice: /Stage[main]/Apt/File[preferences]/ensure: created
==> default: Debug: /Stage[main]/Apt/File[preferences]: The container Class[Apt] will propagate my refresh event
==> default: Info: /Stage[main]/Apt/File[preferences]: Scheduling refresh of Class[Apt::Update]
==> default: Info: Class[Apt::Update]: Scheduling refresh of Exec[apt_update]
<strong>==> default: Debug: Exec[apt_update](provider=posix): Executing '/usr/bin/apt-get update'
==> default: Debug: Executing '/usr/bin/apt-get update'</strong>
</pre>

Looks like things aren't happening in the correct order. The package install happens before the refresh of package lists.

**Comment by jamesnetherton** [comment]
Should be fixed. Version 0.2.1 published to the forge.

**Comment by kwv** [comment]
thanks.   that fixed it
